# Microservicio Estudiante - Backend GenSof
name: Microservicio Estudiante - Backend GenSof 

 # Se ejecuta en cuando se hace un push a la rama main  o dev 
on:
 
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  

  # Sirve para ejecutar el workflow manualmente
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Se llama api-estudiante que es el microservicio
  api-estudiante:
    # Se ejecuta en ubuntu, crea una instancia de ubuntu y se ejecuta el script
    runs-on: ubuntu-latest

    env:
      MYSQLUSER: ${{ secrets.MYSQLUSER }}
      MYSQLPASSWORD: ${{ secrets.MYSQLPASSWORD }}
      MYSQLHOST: ${{ secrets.MYSQLHOST }}	
      MYSQLPORT: ${{ secrets.MYSQLPORT }}	
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}	
      EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      
    # Secuencia de pasos que se van a ejecutar en el microservicio 
    steps:
      # Clona el repositorio del microservicio api-estudiante 
      - uses: actions/checkout@v4

      # Imprime los archivos del repositorio
      - name: Listar archivos
        run: ls -la  # Ahora puedes ver los archivos del repo

      # Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Ejecutar test
      - name: Ejecutar Tests - pytest
        run: pytest -v --maxfail=1 --disable-warnings